### ISSUE TITLE
시퀄라이즈 실습 중 오류

### ISSUE THREAD

**Issue by kwonmory** [ZeroCho/nodejs-book#20]
안녕하세요.
오류가 나네요. 다음이 오류입니다. 

```
db.User = require('./user')(sequelize, Sequelize);
// db.Comment = require('./comment')(sequelize, Sequelize);

// db.User.hasMany(db.Comment, { foreignKey : 'commenter', sourceKey : 'id'});
// db.Comment.belongsTo(db.User, { foreignKey : 'commentar', targetKey : 'id'});

```
에서 저 부분에서 오류가 나네요.. 왜 그럴까요 ㅠ 책 그대로 따라한건데;;

페이지수는 전자책이라 정확히는 모르겠고 시퀄라이즈 실습하기 맨 앞부분입니다. 

## 오류 화면
```
crypto.js:99
  this._handle.update(data, encoding);
               ^

TypeError: Data must be a string or a buffer
    at Hash.update (crypto.js:99:16)
    at sha1 (/Users/morykwon/Documents/project/learn-sequelize/node_modules/mysql2/lib/auth_41.js:31:8)
    at Object.token [as calculateToken] (/Users/morykwon/Documents/project/learn-sequelize/node_modules/mysql2/lib/auth_41.js:65:18)
    at new HandshakeResponse (/Users/morykwon/Documents/project/learn-sequelize/node_modules/mysql2/lib/packets/handshake_response.js:28:26)
    at ClientHandshake.sendCredentials (/Users/morykwon/Documents/project/learn-sequelize/node_modules/mysql2/lib/commands/client_handshake.js:51:31)
    at ClientHandshake.handshakeInit (/Users/morykwon/Documents/project/learn-sequelize/node_modules/mysql2/lib/commands/client_handshake.js:137:12)
    at ClientHandshake.execute (/Users/morykwon/Documents/project/learn-sequelize/node_modules/mysql2/lib/commands/command.js:39:22)
    at Connection.handlePacket (/Users/morykwon/Documents/project/learn-sequelize/node_modules/mysql2/lib/connection.js:455:32)
    at PacketParser.onPacket (/Users/morykwon/Documents/project/learn-sequelize/node_modules/mysql2/lib/connection.js:73:18)
    at PacketParser.executeStart (/Users/morykwon/Documents/project/learn-sequelize/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/Users/morykwon/Documents/project/learn-sequelize/node_modules/mysql2/lib/connection.js:80:31)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:601:20)
```

**Comment by kwonmory** [comment]
흑흑...

알고보니 "Data must be a string or a buffer" 랑 똑같이 데이터에 값이 문자열값이 아니였다는건데..
config 에 password 보니깐 숫자로 써놨네요.. ㅠㅠ

### 해결 완료
