### ISSUE TITLE
9.2 데이터베이스 세팅하기 user.js에서 오류가 납니다. 

### ISSUE THREAD

**Issue by kwan-yoon** [ZeroCho/nodejs-book#295]
TypeError: this.sequelize.isDefined is not a function
    at Function.init (C:\workspace\vscode_workspace\nodebird\node_modules\sequelize\lib\model.js:699:24)
    at Function.init (C:\workspace\vscode_workspace\nodebird\models\user.js:5:22)
    at Object.<anonymous> (C:\workspace\vscode_workspace\nodebird\models\index.js:18:6)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\workspace\vscode_workspace\nodebird\app.js:10:23)

데이터베이스 세팅하기에 코드를 따라하고 npm start를 하면 계속 위와 같은 오류가 뜨네요.
아래는 소스 전문입니다. 왜 나는지 모르겠어서 질문드립니다.

const Sequelize = require('sequelize');

module.exports = class User extends Sequelize.Model {
    static init(sequelize) {
        return super.init({
            email: {
                type: Sequelize.STRING(40),
                allowNull: true,
                unique: true
            },
            nick: {
                type: Sequelize.STRING(15),
                allowNull: false
            },
            password: {
                type: Sequelize.STRING(100),
                allowNull: true
            },
            provider: {
                type: Sequelize.STRING(10),
                allowNull: false,
                defaultValue: 'local' 
            },
            snsId: {
                type: Sequelize.STRING(30),
                allowNull: true
            }
        }, {
            sequelize,
            timestamps: true,
            underscored: false,
            modelName: 'User',
            tableName: 'users',
            paranoid: true,
            charset: 'utf8',
            collate: 'utf8_general_ci'
        });
    }

    static associate(db) {
        db.User.hasMany(db.Post);
        db.User.belongsToMany(db.User, {
            foreignKey: 'followingId',
            as: 'Followers',
            through: 'Follow'
        });
        db.User.belongsToMany(db.User, {
            foreignKey: 'followerId',
            as: 'Followings',
            through: 'Follow'
        });
    }
};

**Comment by ZeroCho** [comment]
model/index.js에서 init함수 인수를 잘못넣으신 것 같습니다.

**Comment by kwan-yoon** [comment]
index.js에서는 오타가 없는데, 자꾸 에러가 나더라구요.
선생님이 제공해주신 소스파일들로 대체해서 진행하였습니다.
감사합니다.
